---
extends: default

ignore: |
  vault.yml

rules:
  braces:
    min-spaces-inside: 1
    max-spaces-inside: 1
  comments:
    min-spaces-from-content: 1
  line-length:
    max: 120
    level: warning
  truthy:
    allowed-values: ["true", "false"]
