---
- name: Install Python build deps
  become: true
  ansible.builtin.apt:
    name:
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - curl
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libxml2-dev
      - libxmlsec1-dev
      - libffi-dev
      - liblzma-dev
    state: present
    update_cache: true

- name: Install unarchive dependencies
  become: true
  ansible.builtin.apt:
    name:
      - gzip
      - tar
    state: present
